import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";
import AuthProvider from "@/AuthProvider/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home Decor",
  
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
    <meta charSet="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Home Decor</title>
    <meta name="description" content={metadata.description} />
    <link rel="icon" type="image/svg+xml" href="https://i.ibb.co/7tcxRQb/logo-removebg-preview.png" />
  </head>
  <body className={inter.className}>
     <AuthProvider>
      <Navbar/>
    <main>
    {children}
    </main>
      <Footer/>
     </AuthProvider>
     </body>
    </html>
  );
}
